### ISSUE TITLE
Travis fails to create temporary directory

### ISSUE THREAD

**Issue by espadrine** [lloyd/ass#9]
I talked to them on [Twitter as well](https://twitter.com/espadrine/status/505100041154199552).

https://travis-ci.org/badges/shields/builds/32789852

**Comment by jrgm** [comment]
Add this to .travis.yml, workaround for obsolete `temp` module 0.6   

```
env:
  global:
    - TMPDIR=/tmp
```

The correct fix is to upgrade the temp module, but the above will workaround in your badges tree in the meantime.

**Comment by jrgm** [comment]
Hi, I've published v0.0.6 to npmjs.org. Let me know if that works for you!

**Comment by espadrine** [comment]
Thanks a lot! It works! <3
